name:               'Finance::Currency::Convert - Convert currencies and fetch their exchange rates'
abstract:           'Convert currencies and fetch their exchange rates'
author:
    - Jan Willamowius <jan@willamowius.de>
license:            perl
distribution_type:  module
recommends:
    Finance::Quote:  0
resources:
  license: https://dev.perl.org/licenses/
  homepage: https://www.willamowius.de/perl.html
